'use strict';
const D=window.PORTAL_DATA,$=id=>document.getElementById(id), colors=['#67bafa','#f4b76f','#b199e8','#42c9a0','#f17d87'];
const valid=D.assets.filter(a=>a.meta.status==='PASS'), commodities=D.assets.filter(a=>a.meta.status==='PRICE_ONLY');
const escapeHTML=x=>String(x??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=(x,d=2)=>x===null||x===undefined||!Number.isFinite(Number(x))?'N/A':Number(x).toLocaleString('en-US',{maximumFractionDigits:d,minimumFractionDigits:d});
const pct=x=>x==null?'N/A':num(x*100)+'%';
let tab='overview';
const inScope=m=>(!$('scopeRegion').value||m.investment_region===$('scopeRegion').value)&&(!$('scopeGroup').value||m.asset_class===$('scopeGroup').value);
const scopedValid=()=>valid.filter(a=>inScope(a.meta));
const scopedAudit=()=>D.audit.filter(inScope);
const metric=a=>a.analytics[$('scopeWindow').value];
const available=()=>scopedValid().filter(a=>metric(a)?.metric_status==='AVAILABLE');
const config={responsive:true,displaylogo:false,scrollZoom:true,displayModeBar:true,toImageButtonOptions:{format:'png',scale:2},modeBarButtonsToRemove:['lasso2d','select2d']};
const base=()=>({paper_bgcolor:'#111d30',plot_bgcolor:'#111d30',font:{family:'Segoe UI,Arial',color:'#aebed2',size:12},margin:{l:72,r:28,t:40,b:70},hovermode:'x unified',dragmode:'zoom',legend:{orientation:'h',y:1.13,x:0},xaxis:{gridcolor:'#24344a',showspikes:true,spikemode:'across',spikesnap:'cursor',rangeslider:{visible:false}},yaxis:{gridcolor:'#24344a',automargin:true,zerolinecolor:'#40516a',fixedrange:false}});
function rangeY(traces,range){let lo=Infinity,hi=-Infinity;const left=range?Date.parse(range[0]):-Infinity,right=range?Date.parse(range[1]):Infinity;
 for(const t of traces){if(t.visible===false||t.visible==='legendonly')continue;const arrays=t.type==='candlestick'?[t.low,t.high]:[t.y];
 for(let i=0;i<(t.x||[]).length;i++){const x=Date.parse(t.x[i]);if(x<left||x>right)continue;for(const a of arrays){const y=a?.[i];if(typeof y==='number'&&Number.isFinite(y)){lo=Math.min(lo,y);hi=Math.max(hi,y);}}}}
 if(!Number.isFinite(lo))return null;const pad=(hi-lo||Math.abs(hi)*.02||1)*.07;return [lo-pad,hi+pad];}
window.portalRangeY=rangeY;
function autoscale(id){const el=$(id);if(!el.data)return;const r=el.layout.xaxis?.autorange?null:el.layout.xaxis?.range;const y=rangeY(el.data,r);if(y)Plotly.relayout(el,{'yaxis.range':y,'yaxis.autorange':false});}
async function timeChart(id,traces,unit){$(id).innerHTML='';const clean=traces.map((t,i)=>{const v=structuredClone(t);delete v.xaxis;delete v.yaxis;v.line={...v.line,color:colors[i%colors.length],width:i?1.4:2};return v;});
 const layout=base();layout.yaxis.title={text:unit};layout.xaxis.type='date';
 const yr=rangeY(clean,null);if(yr)layout.yaxis.range=yr;
 await Plotly.newPlot(id,clean,layout,config);const el=$(id);
 el.on('plotly_relayout',ev=>{if(Object.keys(ev).some(k=>k.startsWith('xaxis.range')||k==='xaxis.autorange'))autoscale(id);});
 el.on('plotly_restyle',()=>autoscale(id));}
function table(id,rows,cols){if(!rows.length){$(id).innerHTML='<p class="empty">No instruments match the current filters.</p>';return;}$(id).innerHTML='<table><thead><tr>'+cols.map(c=>'<th>'+escapeHTML(c[0])+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+cols.map(c=>'<td>'+( (v=>v&&typeof v==='object'&&v.__html?v.__html:escapeHTML(v))(typeof c[1]==='function'?c[1](r):r[c[1]]) )+'</td>').join('')+'</tr>').join('')+'</tbody></table>';}
function bars(id,rows,value,unit){rows=rows.filter(r=>Number.isFinite(value(r)));if(!rows.length){emptyCharts([id]);return;}$(id).innerHTML='';const layout=base();layout.hovermode='closest';layout.margin.l=160;layout.margin.b=60;layout.xaxis={title:{text:unit},gridcolor:'#24344a',zerolinecolor:'#91a3ba'};layout.yaxis={automargin:true};$(id).style.height=Math.max(360,rows.length*29+90)+'px';return Plotly.newPlot(id,[{type:'bar',orientation:'h',y:rows.map(r=>r.name),x:rows.map(value),marker:{color:rows.map(r=>value(r)>=0?colors[0]:colors[4])},hovertemplate:'%{y}: %{x:.2f}<extra></extra>'}],layout,config);}
function options(id,assets){$(id).innerHTML=assets.map(a=>'<option value="'+escapeHTML(a.meta.id)+'">'+escapeHTML(a.meta.name)+'</option>').join('');}
function periods(id,charts){$(id).innerHTML=['1M','3M','6M','1Y','3Y','ALL'].map(p=>'<button type="button" data-period="'+p+'">'+p+'</button>').join('')+'<button type="button" data-period="AUTO">Auto Y</button>';
 $(id).onclick=async e=>{const period=e.target.dataset.period;if(!period)return;for(const b of $(id).querySelectorAll('button'))b.classList.toggle('active',b.dataset.period===period);
 for(const chart of charts){const el=$(chart);if(!el.data?.length)continue;if(period==='AUTO'){autoscale(chart);continue;}if(period==='ALL'){await Plotly.relayout(el,{'xaxis.autorange':true});autoscale(chart);continue;}
 const dates=el.data.flatMap(t=>t.x||[]).map(x=>Date.parse(x)).filter(Number.isFinite);if(!dates.length)continue;const end=new Date(Math.max(...dates)),start=new Date(end);start.setUTCMonth(start.getUTCMonth()-({'1M':1,'3M':3,'6M':6,'1Y':12,'3Y':36}[period]));await Plotly.relayout(el,{'xaxis.range':[start.toISOString(),end.toISOString()],'xaxis.autorange':false});autoscale(chart);}};}
function emptyCharts(ids){for(const id of ids){if($(id).data)Plotly.purge(id);$(id).innerHTML='<p class="empty">No eligible observations for the current selection.</p>';}}
async function market(){const a=scopedValid().find(a=>a.meta.id===$('marketAsset').value);if(!a){$('marketInfo').textContent='No eligible OHLC instruments in this selection.';emptyCharts(['price','equity','drawdown','rollsharpe','ewma']);return;}
 const m=a.meta;$('marketInfo').innerHTML='<strong>'+escapeHTML(m.name)+'</strong> · '+escapeHTML(m.symbol)+'<br>Last observation: '+escapeHTML(m.last_date)+' · Full OOS: '+escapeHTML(m.test_start)+' → '+escapeHTML(m.last_date)+' · Net return '+pct(m.total_return)+' · Sharpe '+num(m.sharpe)+'<br>Chart date controls affect chart display only. Comparison-period metrics are available in Performance and Risk.';
 const price=a.traces.filter(t=>!t.yaxis||t.yaxis==='y');
 if($('tradeMarkers').checked)for(const side of [1,-1]){const rows=a.trades.filter(t=>t.direction===side);if(rows.length)price.push({type:'scatter',mode:'markers',x:rows.map(t=>t.entry_date),y:rows.map(t=>t.entry),name:side===1?'Long entry':'Short entry',marker:{symbol:side===1?'triangle-up':'triangle-down',size:9,color:side===1?colors[3]:colors[4]}});}
 await timeChart('price',price,m.currency||'Reference price units');await timeChart('equity',a.traces.filter(t=>t.yaxis==='y2'),'Account units');await timeChart('drawdown',a.traces.filter(t=>t.yaxis==='y3'),'%');
 const y4=a.traces.filter(t=>t.yaxis==='y4'),y5=a.traces.filter(t=>t.yaxis==='y5');
 if(y4.length)await timeChart('rollsharpe',y4,'Sharpe (ann.)');else $('rollsharpe').innerHTML='<div class="notice">Rolling Sharpe needs one full rebuild with the current engine (traces are built at build time).</div>';
 if(y5.length)await timeChart('ewma',y5,'Ann. %');else $('ewma').innerHTML='<div class="notice">EWMA volatility needs one full rebuild with the current engine (traces are built at build time).</div>';
 $('marketPeriods').querySelector('[data-period="1Y"]').click();}
async function commodity(){const a=commodities.filter(a=>inScope(a.meta)).find(a=>a.meta.id===$('commodityAsset').value);if(!a){$('commodityInfo').textContent='No eligible commodity reference series in this selection.';emptyCharts(['commodityChart']);return;}const m=a.meta;$('commodityInfo').innerHTML='<strong>'+escapeHTML(m.name)+'</strong><br>'+escapeHTML(m.provider_name)+' · '+escapeHTML(m.interval)+' · '+escapeHTML(m.unit)+' · Last observation '+escapeHTML(m.last_date);await timeChart('commodityChart',a.traces,m.unit);$('commodityPeriods').querySelector('[data-period="3Y"]').click();}
function median(values){const a=values.filter(Number.isFinite).sort((a,b)=>a-b),n=a.length;return n?(a[Math.floor(n/2)]+a[Math.floor((n-1)/2)])/2:null;}
function overview(){const rows=scopedAudit(),eligible=available(),pass=rows.filter(r=>r.status==='PASS').length,priceOnly=rows.filter(r=>r.status==='PRICE_ONLY').length,rejected=rows.filter(r=>r.status==='REJECTED').length;
 const vals=[['Selected instruments',String(rows.length),'Registered instruments matching both filters'],['Strategy comparisons',eligible.length+' / '+pass,'Window-eligible / accepted OHLC instruments'],['Median Sharpe',num(median(eligible.map(a=>metric(a).sharpe))),eligible.filter(a=>Number.isFinite(metric(a).sharpe)).length+' defined ratios · independent strategies'],['Median max drawdown',pct(median(eligible.map(a=>metric(a).max_drawdown))),eligible.length+' strategies · selected comparison period']];
 $('kpis').innerHTML=vals.map(v=>'<div class="kpi"><small>'+v[0]+'</small><strong>'+v[1]+'</strong><span>'+v[2]+'</span></div>').join('');
 $('coverageNote').textContent='Data coverage in this selection: '+pass+' accepted OHLC · '+priceOnly+' price-only reference series · '+rejected+' rejected. '+(pass-eligible.length)+' accepted OHLC instruments lack the selected comparison window. Missing results are excluded from medians.';
 const regions=[...new Set(rows.map(r=>r.investment_region))];const l=base();l.barmode='stack';l.hovermode='closest';l.margin.l=50;l.margin.b=110;l.yaxis.title={text:'Instrument count'};
 Plotly.newPlot('coverage',['PASS','PRICE_ONLY','REJECTED'].map((s,i)=>({type:'bar',name:['Accepted OHLC','Price only','Rejected'][i],x:regions,y:regions.map(r=>rows.filter(a=>a.investment_region===r&&a.status===s).length),marker:{color:[colors[3],colors[0],colors[4]][i]}})),l,config);
 if(!eligible.length)emptyCharts(['riskReturn']);else{const layout=base();layout.hovermode='closest';layout.xaxis={title:{text:'Annualized strategy volatility (%)'},gridcolor:'#24344a',rangemode:'tozero'};layout.yaxis={title:{text:'Net strategy return (%)'},gridcolor:'#24344a',zerolinecolor:'#91a3ba'};
 Plotly.newPlot('riskReturn',[{type:'scatter',mode:'markers',x:eligible.map(a=>metric(a).volatility*100),y:eligible.map(a=>metric(a).total_return*100),customdata:eligible.map(a=>a.meta.id),text:eligible.map(a=>a.meta.name),marker:{size:12,color:eligible.map(a=>metric(a).total_return>=0?colors[3]:colors[4]),line:{width:1,color:'#e9eff7'}},hovertemplate:'%{text}<br>Volatility: %{x:.2f}%<br>Net return: %{y:.2f}%<extra></extra>'}],layout,config).then(()=>{$('riskReturn').on('plotly_click',e=>openInstrument(e.points[0].customdata));});}
 const byId=new Map(D.assets.map(a=>[a.meta.id,a]));const sort=$('universeSort').value;
 rows.sort((a,b)=>{if(sort==='name')return a.name.localeCompare(b.name);const x=metric(byId.get(a.id)||{analytics:{}})?.[sort],y=metric(byId.get(b.id)||{analytics:{}})?.[sort];if(!Number.isFinite(x))return Number.isFinite(y)?1:a.name.localeCompare(b.name);if(!Number.isFinite(y))return -1;return sort==='max_drawdown'?x-y:y-x;});
 table('universeTable',rows,[['Instrument','name'],['Region','investment_region'],['Instrument group','asset_class'],['Data status','status'],['Last observation','last_date'],['Net return',r=>pct(metric(byId.get(r.id)||{analytics:{}})?.total_return)],['Sharpe',r=>num(metric(byId.get(r.id)||{analytics:{}})?.sharpe)],['Max drawdown',r=>pct(metric(byId.get(r.id)||{analytics:{}})?.max_drawdown)],['Metric availability',r=>{const a=byId.get(r.id),m=a&&metric(a);return m?.metric_status==='AVAILABLE'?'QuantStats '+D.metrics.version:(m?.reason|| (r.status==='PRICE_ONLY'?'No OHLC strategy':r.reason||'Unavailable'));}]]);
 $('universeTable').querySelectorAll('tbody tr').forEach((tr,i)=>{const cell=tr.cells[0];cell.textContent='';const b=document.createElement('button');b.className='instrument-link';b.textContent=rows[i].name;b.onclick=()=>openInstrument(rows[i].id);cell.append(b);});}
function metricRows(){return available().map(a=>({...a.meta,...metric(a)}));}
function regional(){const rows=metricRows();bars('regionalChart',rows,r=>r.total_return*100,'Net strategy return (%)');table('regionalTable',rows,[['Instrument','name'],['Region','investment_region'],['First observation','metric_start'],['Last observation','metric_end'],['Observations','metric_observations'],['Net return',r=>pct(r.total_return)],['Max drawdown',r=>pct(r.max_drawdown)],['Sharpe',r=>num(r.sharpe)]]);}
function performance(){const rows=metricRows();table('performanceTable',rows,[['Instrument','name'],['First observation','metric_start'],['Last observation','metric_end'],['Observations','metric_observations'],['Net return',r=>pct(r.total_return)],['Annualized return',r=>pct(r.cagr)],['Sharpe',r=>num(r.sharpe)],['Sortino',r=>num(r.sortino)],['Calmar',r=>num(r.calmar)],['Undefined metrics',r=>Object.entries(r.metric_reasons).map(([k,v])=>k+': '+v).join('; ')||'None']]);bars('ranking',rows.sort((a,b)=>(a.sharpe??-Infinity)-(b.sharpe??-Infinity)),r=>r.sharpe,'Sharpe ratio');}
function risk(){const rows=metricRows();table('strategyRiskTable',rows,[['Instrument','name'],['Annualized volatility',r=>pct(r.volatility)],['Max drawdown',r=>pct(r.max_drawdown)],['Ulcer index',r=>pct(r.ulcer_index)],['Normal VaR 95%',r=>pct(r.var_95)],['CVaR below normal VaR',r=>pct(r.cvar_95)],['EWMA vol (ann.)',r=>r.ewma_annual_pct==null?'—':num(r.ewma_annual_pct)+'%'],['QuantStats report',r=>r.qs_report?{__html:'<a href="'+encodeURI(r.qs_report)+'" target="_blank" rel="noopener">open</a>'}:'—'],['First observation','metric_start'],['Last observation','metric_end']]);const marketRows=scopedValid().map(a=>a.meta);bars('riskChart',marketRows.filter(r=>Number.isFinite(r.egarch_annual_pct)).sort((a,b)=>a.egarch_annual_pct-b.egarch_annual_pct),r=>r.egarch_annual_pct,'Annualized underlying volatility (%)');table('riskTable',marketRows,[['Instrument','name'],['EGARCH volatility %',r=>num(r.egarch_annual_pct)],['Model status','egarch_status'],['Last observation','last_date']]);}
function trades(){const a=scopedValid().find(a=>a.meta.id===$('tradeAsset').value);table('tradeTable',a?.trades||[],[['Entry date','entry_date'],['Exit date','exit_date'],['Direction',r=>r.direction===1?'Long':'Short'],['Entry price',r=>num(r.entry)],['Exit price',r=>num(r.exit)],['Quantity',r=>num(r.quantity)],['Net P&L',r=>num(r.net_pnl)],['Exit reason','reason']]);}
function audit(){const q=$('auditSearch').value.toLowerCase(),s=$('auditStatus').value;table('auditTable',scopedAudit().filter(r=>(!s||r.status===s)&&(r.name+' '+(r.symbol||'')).toLowerCase().includes(q)),[['Instrument','name'],['Region','investment_region'],['Instrument group','asset_class'],['Symbol','symbol'],['Data status','status'],['Last observation','last_date'],['Observations','observations'],['Reason','reason']]);}
function methodology(){const m=D.metrics;$('metricMethod').textContent=m.engine+' '+m.version+' · '+m.annual_bars+' observations/year · configured annual hurdle '+pct(m.annual_rf)+' · '+m.basis;
 const rows=[['Net return','comp','Compounded net OOS strategy returns; first-day P&L is included.'],['Annualized return','cagr','Observation-count annualization: N / configured observations per year. This differs from calendar-year CAGR.'],['Volatility','volatility','Sample standard deviation (ddof=1) multiplied by the square root of observations/year.'],['Sharpe','sharpe','Mean excess return / sample standard deviation, annualized. Constant hurdle converted to daily equivalent.'],['Sortino','sortino','Excess-return downside deviation across all observations; annualized.'],['Calmar','calmar','Annualized compounded return / absolute maximum drawdown; N/A if no drawdown.'],['Max drawdown','max_drawdown','Peak-to-trough strategy equity loss, including initial capital as the accounting baseline.'],['Ulcer index','ulcer_index','QuantStats convention: square root of sum of squared drawdowns divided by N minus 1.'],['Normal VaR 95%','value_at_risk','Normal-distribution 5th-percentile daily return estimate using sample mean and standard deviation.'],['CVaR below normal VaR','conditional_value_at_risk','Mean observed return below the normal VaR threshold; N/A for an empty tail. This is not historical-quantile expected shortfall.']];
 table('definitions',rows.map(r=>({name:r[0],function:'quantstats.stats.'+r[1],definition:r[2]})),[['Metric','name'],['Calculation source','function'],['Definition','definition']]);}
const tabs=[['overview','Executive'],['regional','Regional'],['market','Index Lab'],['commodities','Commodities'],['performance','Performance'],['risk','Risk'],['trades','Trade Log'],['audit','Data Audit'],['methodology','Methodology']];
$('tabs').innerHTML=tabs.map(([id,label])=>'<button type="button" role="tab" id="tab-'+id+'" aria-controls="'+id+'" aria-selected="'+(id===tab)+'" data-tab="'+id+'">'+label+'</button>').join('');
for(const [id] of tabs)$(id).setAttribute('aria-labelledby','tab-'+id);
const renders={overview,regional,market,commodities:commodity,performance,risk,trades,audit,methodology};
let renderQueue=Promise.resolve();function renderActive(){renderQueue=renderQueue.then(()=>renders[tab]()).catch(err=>{$('freshness').textContent='Rendering failed: '+err.message;});return renderQueue;}
function selectTab(id){tab=id;for(const [key] of tabs){$(key).hidden=key!==tab;$('tab-'+key).setAttribute('aria-selected',String(key===tab));}return renderActive();}
$('tabs').onclick=e=>{if(e.target.dataset.tab)selectTab(e.target.dataset.tab);};
$('tabs').onkeydown=e=>{const list=[...$('tabs').querySelectorAll('button')];let i=list.indexOf(document.activeElement);if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();i=(i+(e.key==='ArrowRight'?1:-1)+list.length)%list.length;list[i].focus();list[i].click();}};
function keepOptions(id,assets){const old=$(id).value;options(id,assets);if(assets.some(a=>a.meta.id===old))$(id).value=old;$(id).disabled=!assets.length;}
function scopeChanged(){keepOptions('marketAsset',scopedValid());keepOptions('tradeAsset',scopedValid());keepOptions('commodityAsset',commodities.filter(a=>inScope(a.meta)));$('scopeCount').textContent=scopedAudit().length+' of '+D.audit.length+' registered instruments';const w=$('scopeWindow').value;$('windowNote').textContent=(w==='FULL'?'Full OOS: instrument test periods differ.':'Common comparison interval: after '+D.metrics.windows[w]+' through '+D.metrics.common_end+'. Native observation dates may differ.')+' Ratios: QuantStats '+D.metrics.version+' · annual hurdle '+pct(D.metrics.annual_rf)+' · '+D.metrics.annual_bars+' observations/year. Charts and trade logs have separate date controls.';return renderActive();}
for(const [id,field,label] of [['scopeRegion','investment_region','All regions'],['scopeGroup','asset_class','All instrument groups']])$(id).innerHTML='<option value="">'+label+'</option>'+[...new Set(D.audit.map(a=>a[field]))].sort().map(x=>'<option>'+escapeHTML(x)+'</option>').join('');
for(const id of ['scopeRegion','scopeGroup','scopeWindow'])$(id).onchange=scopeChanged;
$('resetScope').onclick=()=>{$('scopeRegion').value='';$('scopeGroup').value='';$('scopeWindow').value='1Y';scopeChanged();};
function openInstrument(id){const a=D.assets.find(a=>a.meta.id===id);if(!a){$('auditSearch').value=D.audit.find(r=>r.id===id)?.name||'';$('auditStatus').value='';selectTab('audit');return;}if(a.meta.status==='PRICE_ONLY'){$('commodityAsset').value=id;selectTab('commodities');}else{$('marketAsset').value=id;selectTab('market');}}
periods('marketPeriods',['price','equity','drawdown','rollsharpe','ewma']);periods('commodityPeriods',['commodityChart']);
for(const id of ['marketAsset','tradeMarkers','commodityAsset','tradeAsset'])$(id).onchange=renderActive;
$('auditSearch').oninput=audit;$('auditStatus').onchange=audit;$('universeSort').onchange=overview;$('goAudit').onclick=()=>{$('auditSearch').value='';$('auditStatus').value='REJECTED';selectTab('audit');};
$('exportTrades').onclick=()=>{const a=scopedValid().find(a=>a.meta.id===$('tradeAsset').value);if(!a?.trades.length)return;const keys=Object.keys(a.trades[0]);const safe=v=>'"'+String(v??'').replace(/"/g,'""').replace(/^[=+@]/,"'")+'"';const csv=[keys,...a.trades.map(r=>keys.map(k=>r[k]))].map(row=>row.map(safe).join(',')).join('\n');const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8;'}));const link=document.createElement('a');link.href=url;link.download=a.meta.id+'-trades.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('buildDate').textContent='Rendered: '+D.rendered.slice(0,10);const latest=D.assets.map(a=>a.meta.last_date).sort().at(-1);$('freshness').textContent='Latest daily source observation: '+latest+' · Check instrument-level dates. Re-rendering an existing report does not refresh market data.';
if(D.source_generated){const hours=(Date.now()-Date.parse(D.source_generated))/3600000;if(hours>36)$('freshness').textContent+=' DATA UPDATE WARNING: source report age '+Math.floor(hours)+' hours.';}
window.addEventListener('resize',()=>document.querySelectorAll('section:not([hidden]) .js-plotly-plot').forEach(el=>Plotly.Plots.resize(el)));
document.querySelector('details').addEventListener('toggle',()=>{if($('coverage').data)Plotly.Plots.resize('coverage');});
scopeChanged();
